(ns vendor
  "Vendored-elisp updater for pod-kpassapk-emacs.

    bb vendor            update every vendored library to upstream HEAD
    bb vendor <lib> ...  update only the named libraries (see `libs`)

  For each library this shallow-clones the upstream repo, copies the
  vendored files into vendor/, and rewrites the pin table in
  vendor/README.md with the new revision. The files are embedded into
  the pod binary (src/elisp.rs), so run `bb test` after updating."
  (:require [babashka.fs :as fs]
            [babashka.process :refer [shell]]
            [clojure.java.io :as io]
            [clojure.string :as str]))

(def libs
  "lib name -> upstream repo, license, and the files vendored from its root."
  (array-map
   "cljbang"  {:repo "https://github.com/borkdude/cljbang.el"
               :license "MIT"
               :files ["cljbang.el" "cljbang-core.el" "cljbang-string.el"]}
   "parseclj" {:repo "https://github.com/clojure-emacs/parseclj"
               :license "GPL-3.0"
               :files ["parseclj.el" "parseclj-alist.el" "parseclj-ast.el"
                       "parseclj-lex.el" "parseclj-parser.el"]}
   "parseedn" {:repo "https://github.com/clojure-emacs/parseedn"
               :license "GPL-3.0"
               :files ["parseedn.el"]}
   "a"        {:repo "https://github.com/plexus/a.el"
               :license "GPL-3.0"
               :files ["a.el"]}
   "bencode"  {:repo "https://github.com/skeeto/emacs-bencode"
               :license "Unlicense"
               :files ["bencode.el"]}))

(def root
  (-> *file* io/file .getCanonicalFile .getParentFile .getParentFile))

(def vendor-dir (io/file root "vendor"))
(def readme-file (io/file vendor-dir "README.md"))

(defn die [& msg]
  (binding [*out* *err*] (println (apply str "vendor: " msg)))
  (System/exit 1))

(defn sh-out [& args]
  (-> (apply shell {:out :string} args) :out str/trim))

(defn short [sha] (subs sha 0 12))

(defn current-pin
  "The sha pinned in the README for this repo url, or nil."
  [readme-text repo]
  (some (fn [line]
          (when (str/includes? line repo)
            (second (re-find #"`([0-9a-f]{7,40})`" line))))
        (str/split-lines readme-text)))

(defn update!
  "Clone repo, copy its files into vendor/ unless already at the pinned
  sha. Return the sha the library is now pinned at."
  [name {:keys [repo files]} pinned]
  (fs/with-temp-dir [tmp {:prefix "vendor"}]
    (shell "git clone --quiet --depth 1" repo (str tmp))
    (let [sha (sh-out "git" "-C" (str tmp) "rev-parse" "HEAD")]
      (if (= sha pinned)
        (do (println (str "vendor: " name " already at " (short sha)))
            pinned)
        (do (doseq [f files]
              (let [src (fs/file (str tmp) f)]
                (when-not (fs/exists? src)
                  (die f " not found in " repo " @ " (short sha)
                       " — did upstream move it?"))
                (fs/copy src (fs/file vendor-dir f) {:replace-existing true})))
            (println (str "vendor: " name " "
                          (if pinned (str (short pinned) " -> ") "pinned at ")
                          (short sha)))
            sha)))))

(defn readme-text
  "Regenerate vendor/README.md from `libs` and the pins map (name -> sha)."
  [pins]
  (let [row (fn [[name {:keys [repo license files]}]]
              (str "| " (str/join ", " (map #(str "`" % "`") files))
                   " | " repo
                   " | " (if-let [sha (pins name)] (str "`" sha "`") "—")
                   " (" license ") |"))]
    (str "# Vendored elisp\n"
         "\n"
         "Third-party libraries the emacs child loads (`-L vendor`), copied in verbatim\n"
         "and embedded into the pod binary (see `src/elisp.rs`).\n"
         "\n"
         "| Library | Upstream | Pinned |\n"
         "|---|---|---|\n"
         (str/join "\n" (map row libs))
         "\n"
         "\n"
         "To bump: `bb vendor` (all) or `bb vendor <lib> ...` where lib is one of\n"
         (str/join ", " (keys libs)) ". Then run `bb test`.\n"
         "This table is generated by scripts/vendor.clj — edit `libs` there, not here.\n"
         "`cljbang-mode.el` is intentionally not vendored — it is interactive-only.\n")))

(defn main [& args]
  (let [names (or (seq args) (keys libs))]
    (doseq [n names]
      (when-not (contains? libs n)
        (die "unknown library: " n " (known: " (str/join ", " (keys libs)) ")")))
    (let [text (slurp readme-file)
          pins (into {} (for [[n {:keys [repo]}] libs]
                          [n (current-pin text repo)]))
          pins' (reduce (fn [acc n] (assoc acc n (update! n (libs n) (acc n))))
                        pins names)]
      (spit readme-file (readme-text pins'))
      (println "vendor: wrote vendor/README.md — now run: bb test"))))

;; Allow running directly too: bb scripts/vendor.clj [lib ...]
(when (= *file* (System/getProperty "babashka.file"))
  (apply main *command-line-args*))
